#include "../controller.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _di_controller_f_a_
  const f_string_t controller_f_a[] = {
    "controller_convert_group_id",
    "controller_convert_user_id",
    "controller_entry_setting_read_map",
    "controller_file_load",
    "controller_file_pid_create",
    "controller_lock_create",
    "controller_rule_copy",
    "controller_rule_expand",
    "controller_path_canonical_relative",
    "controller_validate_environment_name",
    "controller_validate_has_graph",
    "f_account_group_id_by_name",
    "f_capability_from_text",
    "f_console_parameter_process",
    "f_environment_get_all",
    "f_file_exists",
    "f_file_mode_to_mode",
    "f_file_name_base",
    "f_file_remove",
    "f_file_role_change",
    "f_file_stat",
    "f_file_stream_open",
    "f_file_stream_read",
    "f_fss_apply_delimit",
    "f_fss_count_lines",
    "f_memory_array_increase",
    "f_memory_array_increase_by",
    "f_memory_array_resize",
    "f_memory_arrays_resize",
    "f_path_current",
    "f_rip_dynamic_partial",
    "f_rip_dynamic_partial_nulless",
    "f_socket_bind",
    "f_socket_create",
    "f_string_append_assure",
    "f_string_dynamic_append",
    "f_string_dynamic_append_assure",
    "f_string_dynamic_append_nulless",
    "f_string_dynamic_partial_append",
    "f_string_dynamic_partial_append_nulless",
    "f_string_dynamic_partial_mash_nulless",
    "f_string_maps_append",
    "f_thread_create",
    "f_time_spec_millisecond",
    "fl_conversion_dynamic_partial_to_signed_detect",
    "fl_conversion_dynamic_partial_to_unsigned_detect",
    "fl_conversion_dynamic_to_unsigned_detect ",
    "fl_environment_load_names",
    "fl_fss_extended_list_content_read",
    "fl_fss_extended_list_object_read",
    "fl_fss_extended_object_read",
    "fl_iki_read",
    "fll_control_group_prepare",
    "fll_execute_into",
    "fll_execute_program",
    "fll_fss_basic_list_read",
    "fll_fss_extended_read",
    "fll_fss_extended_content_read",
    "fll_fss_extended_list_content_read",
    "fll_program_parameter_process_context_standard",
    "fll_program_parameter_process_verbosity_standard",
  };
#endif // _di_controller_f_a_

#ifdef __cplusplus
} // extern "C"
#endif
